# Generated by Django 3.0.5 on 2020-05-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20200512_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
