# Generated by Django 3.0.5 on 2020-05-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.User')),
            ],
        ),
    ]
