# Generated by Django 3.0.5 on 2020-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_modelsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='email'),
        ),
    ]
