# Generated by Django 3.0.5 on 2020-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
